# Generated by Django 3.2.9 on 2022-04-04 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='name',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='variantDescription',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='readyToShip',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='variant',
            name='_id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
