# Generated by Django 3.2.9 on 2022-03-26 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('root', 'Root'), ('featured', 'Featured'), ('product', 'Product'), ('brand', 'Brand'), ('collection', 'Collection')], default='root', max_length=20),
        ),
        migrations.CreateModel(
            name='ProductDetailsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(max_length=200)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='base.product')),
            ],
        ),
    ]
