# Generated by Django 3.2.9 on 2022-04-25 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20220425_1418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='userId',
            new_name='user',
        ),
    ]
