# Generated by Django 4.0 on 2021-12-22 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('base', '0002_alter_extrauserinfo_otp_createdat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrauserinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extra', to='auth.user'),
        ),
    ]
