# Generated by Django 3.2.9 on 2022-04-10 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20220410_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
