# Generated by Django 3.2.9 on 2022-03-27 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20220326_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='leadTime',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
