# Generated by Django 4.0 on 2021-12-30 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_extrauserinfo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='instructions',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
