# Generated by Django 3.2.9 on 2022-04-10 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_payment_createdat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='createdAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
