# Generated by Django 3.2.9 on 2022-04-10 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_payment_createdat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='paidAt',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='paymentVerified',
        ),
        migrations.AddField(
            model_name='shipment',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
    ]
