# Generated by Django 4.0 on 2021-12-30 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_order_instructions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='address',
            new_name='address_line_1',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='apartment',
            new_name='address_line_2',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='city',
            new_name='postal_code',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='postalCode',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='state',
        ),
        migrations.AddField(
            model_name='order',
            name='paymentId',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='admin_area_1',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='State'),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='admin_area_2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='City'),
        ),
    ]
