# Generated by Django 4.0 on 2021-12-30 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_address_shippingaddress_address_line_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='address_line_1',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='address_line_2',
            new_name='apartment',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='postal_code',
            new_name='city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='instructions',
        ),
        migrations.RemoveField(
            model_name='order',
            name='paymentId',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='admin_area_1',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='admin_area_2',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='postalCode',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='state',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='paymentResult',
            field=models.IntegerField(blank=True, max_length=200, null=True),
        ),
    ]
