# Generated by Django 3.2.9 on 2022-04-20 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_comment_review_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='text',
            new_name='comment',
        ),
    ]
