# Generated by Django 3.2.9 on 2022-04-10 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20220410_1618'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipment',
            old_name='delivered',
            new_name='isDelivered',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='UNVERIFIED_PAID',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='paidItems', to='base.payment'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='shippedItems', to='base.shipment'),
        ),
    ]
