# Generated by Django 4.0 on 2021-12-30 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_address_line_1_shippingaddress_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='instructions',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
