# Generated by Django 3.2.9 on 2022-04-05 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_orderitem_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
    ]
