# Generated by Django 3.2.9 on 2022-04-11 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20220410_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='shipment',
        ),
        migrations.AddField(
            model_name='payment',
            name='shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shippedItems', to='base.shipment'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paidItems', to='base.payment'),
        ),
    ]
