# Generated by Django 4.0 on 2021-12-30 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_order_paymentid_alter_order_paymentresult'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='paymentId',
            new_name='paymentID',
        ),
        migrations.AddField(
            model_name='order',
            name='paymentVerified',
            field=models.BooleanField(default=False),
        ),
    ]
