# Generated by Django 3.2.9 on 2022-04-20 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20220420_2051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extrauserinfo',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='product',
            name='comments',
        ),
        migrations.AddField(
            model_name='comment',
            name='comments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.product'),
        ),
    ]
