# Generated by Django 4.0 on 2021-12-31 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_rename_paymentid_order_paymentid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='paymentResult',
        ),
        migrations.AddField(
            model_name='order',
            name='amountPaid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
