# Generated by Django 4.0 on 2021-12-31 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_remove_order_paymentresult_order_amountpaid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='addressPayPal',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
