# Generated by Django 3.2.9 on 2022-04-20 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_comment_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comments',
            new_name='product',
        ),
    ]
