# Generated by Django 3.2.9 on 2022-01-09 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_order_addresspaypal'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrauserinfo',
            name='taxExempt',
            field=models.BooleanField(default=False),
        ),
    ]
