# Generated by Django 3.2.9 on 2022-03-08 00:42

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_product_display_as_pulldown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=djrichtextfield.models.RichTextField(default=1),
            preserve_default=False,
        ),
    ]
