# Generated by Django 3.2.9 on 2022-03-13 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_alter_product_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='display_as_pulldown',
            new_name='dropdownSelection',
        ),
        migrations.AddField(
            model_name='product',
            name='noMainPicture',
            field=models.BooleanField(default=False),
        ),
    ]
