# Generated by Django 3.2.9 on 2022-03-22 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_alter_category_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['-name']},
        ),
        migrations.AlterModelOptions(
            name='packsize',
            options={'ordering': ['-name']},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'ordering': ['-name']},
        ),
        migrations.AddField(
            model_name='type',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
