# Generated by Django 3.2.9 on 2022-03-22 09:58

from django.db import migrations
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_auto_20220322_0943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='variant',
        ),
        migrations.AlterField(
            model_name='product',
            name='variations',
            field=mptt.fields.TreeManyToManyField(default='None', to='base.Variations'),
        ),
    ]
