# Generated by Django 3.2.9 on 2022-03-23 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pulltest',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
